executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m tree -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m forest -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d adult -m lr -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m tree -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m forest -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d credit -m lr -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m tree -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m forest -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n zero_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n one_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 0 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 1 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 2 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 3 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 4 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 5 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 6 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 7 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 8 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


executable = /home/amir/dev/mace/_venv/bin/python
arguments = batchTest.py -d compass -m lr -n infty_norm -a SAT -b 9 -s 50
error = _cluster_logs/test.$(Process).err
output = _cluster_logs/test.$(Process).out
log = _cluster_logs/test.$(Process).log
request_memory = 8192
request_cpus = 1
queue


